name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
env:
  LATEST_PY_VERSION: '3.9'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .["test"]

      - name: Run Benchmark
        run: python -m pytest --benchmark-only --benchmark-columns 'min, max, mean, median' --benchmark-json output.json

      - name: Push benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmarks
          tool: pytest
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Alert with a commit comment on possible performance regression
          alert-threshold: 200%
          comment-always: true
          fail-on-alert: true
          # Make a commit on `gh-pages` only if main
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          benchmark-data-dir-path: benchmarks
